### ISSUE TITLE
Slider speed and numbering

### ISSUE THREAD

**Issue by dynamiczero99** [NOREADMEStudios/ProjectII#146]
### Expected behavior:
Slider moves at an easy to control speed and with even numbers.
### Actual behavior:
Slider is too fast and uses uneven numbers, which can be bothering.
### Steps to reproduce the problem:
Go to settings from main menu and use the slider with a joystick.
### Version of the game:
b9cc757
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by dynamiczero99** [comment]
Found a pattern: sometimes the slider will increase/decrease by 5 and other times by 4.

**Comment by Margeli** [comment]
Now the slider moves 1% with the buttons, it's more accurate the numbering, in addition it goes slower when it's managed by the axis of the controller to resolve the priblem of "is too fast" --- Branch: Slider
