### ISSUE TITLE
Initial position of the players is incorrect

### ISSUE THREAD

**Issue by dynamiczero99** [NOREADMEStudios/ProjectII#161]
### Expected behavior:
The players should spawn one in each corner.
### Actual behavior:
Players of the same team spawn together in a top corner.
### Steps to reproduce the problem:
Start a match.
### Version of the game:
0.91

Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by Margeli** [comment]
Players position fixed, need to change the direction of the players depending on the side Branch: dev2
