### ISSUE TITLE
Mage ultimate's flames collide with corpses

### ISSUE THREAD

**Issue by dynamiczero99** [NOREADMEStudios/ProjectII#177]
### Expected behavior:
Mage's flames dont collide.
### Actual behavior:
A flame that collides with the corpse is eliminated.
### Steps to reproduce the problem:
Make a player from the opposing team die and then use the mage's ultimate.
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by Margeli** [comment]
done in MargeliBugFixing or merged in dev2 branch
