### ISSUE TITLE
2nd match starts with all players in red team, and unable to change

### ISSUE THREAD

**Issue by dynamiczero99** [NOREADMEStudios/ProjectII#178]
### Expected behavior:
2nd match players can choose their team again.
### Actual behavior:
They all start locked in red team unable to change.
### Steps to reproduce the problem:
End a match and start another one.
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by Normanbg** [comment]
TO CHECK
