### ISSUE TITLE
Items labels and sprites are incorrect

### ISSUE THREAD

**Issue by dynamiczero99** [NOREADMEStudios/ProjectII#190]
### Expected behavior:
The labels show the actual value of the item's effect and the image shows the item.
### Actual behavior:
The labels are incorrect and the items don't show.
### Steps to reproduce the problem:
Go into the item selection screen.
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by dynamiczero99** [comment]
Add items & cursors to general atlas.

**Comment by Normanbg** [comment]
Add items & cursors to general atlas.
