### ISSUE TITLE
ROGUE ult (dash): Change the hit feedback

### ISSUE THREAD

**Issue by albertmas** [NOREADMEStudios/ProjectII#191]
### Expected behavior:
Dagger should be changed for a better indicator
### Actual behavior:
When ult is hit, a dagger appears on top of the enemy hit.
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by albertmas** [comment]
Joel: Create art
Pol: Implement it to code

**Comment by dynamiczero99** [comment]
Added sprite in spells.png.
Position: x - 320, y - 427.
Size: 19x20px.
