### ISSUE TITLE
1v1 win text says Team 2/3 wins

### ISSUE THREAD

**Issue by albertmas** [NOREADMEStudios/ProjectII#197]
### Expected behavior:
It should say "Player 1/2 wins"
### Actual behavior:
It currently says "Team 2/3 wins"
Also in-game UI says 2/3 next to each player and not 1/2
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by Margeli** [comment]
It now says "Team red/blue won" correctly
