### ISSUE TITLE
Slider feedback

### ISSUE THREAD

**Issue by albertmas** [NOREADMEStudios/ProjectII#202]
### Version of the game:
0.96
Please leave a screenshot to clearify the issue.

Thank you for your help

**Comment by dynamiczero99** [comment]
Added two sprites (one for focused, one for unfocused) to atlas.png.
Position (unfocused): x - 1107, y - 197.
Size (unfocused): 45x21px.

**Comment by dynamiczero99** [comment]
Position (focused): x - 1152, y - 197.
Size (focused): 45x21px.

**Comment by Margeli** [comment]
done in margelibugfixing branch or merged in dev2
